apiVersion: v1
kind: PersistentVolume
metadata:
  name: qorus-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: qorusshare
    readOnly: false
  mountOptions:
  - dir_mode=0755
  - file_mode=0644
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qorus-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
