kind: PersistentVolume
apiVersion: v1
metadata:
  name: qorus-pv-init
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/local/qorus-k8s/init"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qorus-pv-claim-init
  labels:
    app: qorus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
