apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qorus
  labels:
    app: qorus
    qorus: master
spec:
  serviceName: "qorus"
  replicas: 1
  selector:
    matchLabels:
      app: qorus
      qorus: master
  template:
    metadata:
      labels:
        app: qorus
        qorus: master
    spec:
      containers:
      - name: qorus
        image: public.ecr.aws/qorus/qorus-ee:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "400m"
            memory: 1Gi
          requests:
            cpu: "200m"
            memory: 512Mi
        env:
        - name: QORUS_TZ
          value: "Europe/Prague"
        - name: QORUS_NO_INIT
          value: "1"
        - name: QORUS_INDEPENDENT_MODE
          value: "1"
        - name: QORUS_DUMB_INIT
          value: "0"
        volumeMounts:
        - name: qorus-user
          mountPath: /opt/qorus/user
        - name: qorus-etc
          mountPath: /opt/qorus/etc
        - name: qorus-log
          mountPath: /opt/qorus/log
        - name: qorus-init
          mountPath: /opt/qorus/init
      initContainers:
      - name: qorus-init
        image: public.ecr.aws/qorus/qorus-ee:latest
        resources:
          limits:
            cpu: "400m"
            memory: 1Gi
          requests:
            cpu: "200m"
            memory: 512Mi
        env:
        - name: QORUS_TZ
          value: "Europe/Prague"
        - name: OMQ_DB_NAME
          value: postgres
        - name: OMQ_DB_TYPE
          value: pgsql
        - name: OMQ_DB_HOST
          value: qorus-postgres
        - name: OMQ_DB_USER
          value: postgres
        - name: OMQ_DB_PASS
          value: omq
        - name: QORUS_INIT_ONLY
          value: "1"
        - name: QORUS_MULTINODE
          value: "1"
        volumeMounts:
        - name: qorus-user
          mountPath: /opt/qorus/user
        - name: qorus-etc
          mountPath: /opt/qorus/etc
        - name: qorus-log
          mountPath: /opt/qorus/log
        - name: qorus-init
          mountPath: /opt/qorus/init
      volumes:
      - name: qorus-user
        nfs:
          server: 192.168.20.23
          path: "/local/qorus-k8s/user"
      - name: qorus-etc
        nfs:
          server: 192.168.20.23
          path: "/local/qorus-k8s/etc"
      - name: qorus-log
        nfs:
          server: 192.168.20.23
          path: "/local/qorus-k8s/log"
      - name: qorus-init
        nfs:
          server: 192.168.20.23
          path: "/local/qorus-k8s/init"
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      imagePullSecrets:
      - name: qorus-secret
