apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: qorus
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: qorus
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 200M
